# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AuthenticationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthenticationWindow(object):
    def setupUi(self, AuthenticationWindow):
        AuthenticationWindow.setObjectName("AuthenticationWindow")
        AuthenticationWindow.resize(266, 172)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AuthenticationWindow.sizePolicy().hasHeightForWidth())
        AuthenticationWindow.setSizePolicy(sizePolicy)
        AuthenticationWindow.setMinimumSize(QtCore.QSize(266, 172))
        AuthenticationWindow.setMaximumSize(QtCore.QSize(266, 172))
        self.widget = QtWidgets.QWidget(AuthenticationWindow)
        self.widget.setGeometry(QtCore.QRect(10, 10, 242, 152))
        self.widget.setObjectName("widget")
        self.authenticationPrompt_layout = QtWidgets.QVBoxLayout(self.widget)
        self.authenticationPrompt_layout.setContentsMargins(0, 0, 0, 0)
        self.authenticationPrompt_layout.setObjectName("authenticationPrompt_layout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.authenticationPrompt_layout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.authenticationPrompt_layout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.authenticationPrompt_layout.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.username_lbl = QtWidgets.QLabel(self.widget)
        self.username_lbl.setObjectName("username_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.username_lbl)
        self.password_lbl = QtWidgets.QLabel(self.widget)
        self.password_lbl.setObjectName("password_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password_lbl)
        self.password_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_lineEdit)
        self.username_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_lineEdit)
        self.authenticationPrompt_layout.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.authenticationPrompt_layout.addItem(spacerItem2)
        self.login_btn = QtWidgets.QPushButton(self.widget)
        self.login_btn.setObjectName("login_btn")
        self.authenticationPrompt_layout.addWidget(self.login_btn)

        self.retranslateUi(AuthenticationWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthenticationWindow)

    def retranslateUi(self, AuthenticationWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthenticationWindow.setWindowTitle(_translate("AuthenticationWindow", "Form"))
        self.label.setText(_translate("AuthenticationWindow", "Student Database Authentication"))
        self.username_lbl.setText(_translate("AuthenticationWindow", "Username"))
        self.password_lbl.setText(_translate("AuthenticationWindow", "Password"))
        self.login_btn.setText(_translate("AuthenticationWindow", "Login"))
